const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Mouse,
		C3.Plugins.Sprite,
		C3.Behaviors.bound,
		C3.Behaviors.Bullet,
		C3.Behaviors.Flash,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Behaviors.EightDir,
		C3.Behaviors.Timer,
		C3.Behaviors.destroy,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Behaviors.Fade,
		C3.Plugins.LocalStorage,
		C3.Plugins.Button,
		C3.Plugins.Browser,
		C3.Behaviors.Anchor,
		C3.Plugins.Audio,
		C3.Behaviors.Tween,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Audio.Acts.PlayAtObjectByName,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Browser.Acts.GoToURLWindow
	];
};
self.C3_JsPropNameTable = [
	{Mouse: 0},
	{vidaZ: 0},
	{RestritoAoLayout: 0},
	{Projétil: 0},
	{Flash: 0},
	{Sólido: 0},
	{zombie: 0},
	{Sprite3: 0},
	{hp: 0},
	{maxHP: 0},
	{cadência_de_tiro: 0},
	{CentrarEm: 0},
	{"8Direções": 0},
	{Cronômetro: 0},
	{Piscar: 0},
	{Cronômetro_da_cadência: 0},
	{Cronômetro_recarregamento: 0},
	{player: 0},
	{DestruirForaDoLayout: 0},
	{bala: 0},
	{Keyboard: 0},
	{score: 0},
	{Esmaecer: 0},
	{caixa_mun: 0},
	{barraVida: 0},
	{barraMorte: 0},
	{Texto: 0},
	{Texto2: 0},
	{ArmazenamentoLocal: 0},
	{Botão: 0},
	{Jogar: 0},
	{Sprite: 0},
	{site: 0},
	{Navegador: 0},
	{Sprite2: 0},
	{Âncora: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Audio: 0},
	{Tween: 0},
	{continuar: 0},
	{desistir: 0},
	{Sprite6: 0},
	{municao_atual: 0},
	{municao_recarregável: 0},
	{recarregando: 0},
	{municaoMaximaNoPente: 0},
	{onda_atual: 0},
	{zumbis_vivos: 0},
	{zumbis_para_spawnar: 0},
	{pausa_entre_ondas: 0},
	{recorde_global: 0},
	{jogo_pausado: 0}
];

self.InstanceType = {
	Mouse: class extends self.IInstance {},
	zombie: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	bala: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	score: class extends self.ITextInstance {},
	caixa_mun: class extends self.ISpriteInstance {},
	barraVida: class extends self.ISpriteInstance {},
	barraMorte: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Texto2: class extends self.ITextInstance {},
	ArmazenamentoLocal: class extends self.IInstance {},
	Botão: class extends self.IButtonInstance {},
	Jogar: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	site: class extends self.ISpriteInstance {},
	Navegador: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	continuar: class extends self.ISpriteInstance {},
	desistir: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {}
}